export const PROOFBENCH_ABI = [
  {
    type: "function",
    name: "submitAttack",
    stateMutability: "payable",
    inputs: [
      { name: "benchmarkId", type: "uint256" },
      { name: "attackHash", type: "bytes32" },
    ],
    outputs: [{ name: "attackId", type: "uint256" }],
  },
  {
    type: "function",
    name: "reportResult",
    stateMutability: "nonpayable",
    inputs: [
      { name: "attackId", type: "uint256" },
      { name: "breached", type: "bool" },
      { name: "resultHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claimReward",
    stateMutability: "nonpayable",
    inputs: [{ name: "attackId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getAttack",
    stateMutability: "view",
    inputs: [{ name: "attackId", type: "uint256" }],
    outputs: [
      { name: "benchmarkId", type: "uint256" },
      { name: "attacker", type: "address" },
      { name: "attackHash", type: "bytes32" },
      { name: "stake", type: "uint256" },
      { name: "timestamp", type: "uint64" },
      { name: "status", type: "uint8" },
      { name: "breached", type: "bool" },
      { name: "resultHash", type: "bytes32" },
      { name: "reward", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "reputation",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "int256" }],
  },
  {
    type: "function",
    name: "successfulAttacks",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "nextAttackId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "minStake",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "benchmarks",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "targetModelHash", type: "bytes32" },
      { name: "version", type: "string" },
      { name: "creator", type: "address" },
      { name: "rewardPool", type: "uint256" },
      { name: "exists", type: "bool" },
    ],
  },
  {
    type: "event",
    name: "AttackSubmitted",
    inputs: [
      { name: "attackId", type: "uint256", indexed: true },
      { name: "benchmarkId", type: "uint256", indexed: true },
      { name: "attacker", type: "address", indexed: true },
      { name: "attackHash", type: "bytes32", indexed: false },
      { name: "stake", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ResultReported",
    inputs: [
      { name: "attackId", type: "uint256", indexed: true },
      { name: "breached", type: "bool", indexed: false },
      { name: "resultHash", type: "bytes32", indexed: false },
      { name: "reputationDelta", type: "int256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RewardPaid",
    inputs: [
      { name: "attackId", type: "uint256", indexed: true },
      { name: "attacker", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;
