export const AD_SLOT_ABI = [
  {
    type: "constructor",
    inputs: [{ name: "roundDurationBlocks_", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "adSetForRound",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bid",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "current",
    inputs: [],
    outputs: [
      { name: "roundId_", type: "uint256", internalType: "uint256" },
      { name: "highestBidder_", type: "address", internalType: "address" },
      { name: "highestBid_", type: "uint256", internalType: "uint256" },
      { name: "endBlock_", type: "uint256", internalType: "uint256" },
      { name: "headline_", type: "string", internalType: "string" },
      { name: "link_", type: "string", internalType: "string" },
      { name: "pendingWinner_", type: "address", internalType: "address" },
      { name: "adSetForRound_", type: "bool", internalType: "bool" },
      { name: "roundDurationBlocks_", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "endBlock",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "headline",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "highestBid",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "highestBidder",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "link",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingWinner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundDurationBlocks",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roundId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setAd",
    inputs: [
      { name: "headline_", type: "string", internalType: "string" },
      { name: "link_", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settle",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AdSet",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "advertiser", type: "address", indexed: true, internalType: "address" },
      { name: "headline", type: "string", indexed: false, internalType: "string" },
      { name: "link", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Bid",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "bidder", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundStarted",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "endBlock", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Settled",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "winner", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
] as const;
